name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        default: '0.1.0'
        required: false
      overwrite-w:
        description: 'If existing version should be overriden'
        default: false
        required: false
        type: boolean

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Print name
        run: |
          echo ${GITHUB_REPOSITORY#*/}
          echo "${GITHUB_REPOSITORY#*/}"
          echo "${github.repository#*/}"

