name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        default: '0.1.0'
        required: false
      overwrite-w:
        description: 'If existing version should be overriden'
        default: false
        required: false
        type: boolean

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Print name
        run: |
          mod_version=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          if [ "$mod_version" == "${{inputs.version}}" ]; then
            echo "UPDATED=true" >> $GITHUB_ENV
          else
            echo "UPDATED=false" >> $GITHUB_ENV
          fi
      - name: Print info
        run: |
          echo "Overwrite ${{ inputs.overwrite-w }}"
          if [ "$UPDATED" == "true" ] && [ "${{ inputs.overwrite-w }}" == "false" ]; then
            echo "ERROR. Version already exists"
          elif [ "$UPDATED" == "true" ]; then
            echo "Overwriting version"
          else
            echo "Updating version"
          fi
      - name: Get Latest Release
        id: get_release
        run: |
          mkdir -p build
          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ inputs.version }}"
          RELEASE_JSON=$(curl -sSL $RELEASE_URL)
          CHANGELOG=$RELEASE_JSON | jq -r '.body'
          if [ $CHANGELOG == "null" ]; then
            echo "No changelog found"
          else
            echo "$CHANGELOG"
          fi
