name: Test

on: workflow_dispatch

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: |
          REPO_LINK="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          echo "Repositgory Link: $REPO_LINK"
          echo "URL: ${GITHUB_SERVER_URL}"
          echo "Name: ${GITHUB_REPOSITORY}"
          echo "Name 2: ${GITHUB_REPOSITORY#*/}"