name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        default: '0.1.0'
        required: false

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: |
          updated=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]') == ${{inputs.version}}
          echo "IS_ALREADY_UPDATED=updated" >> $GITHUB_ENV
          echo "Is already updated: updated"